export type Person = {id:number;name:string;email:string;role:string;department:string;manager_id?:number;active?:boolean};
export type Flow = {id:number;name:string;category:string;min_amount:number;max_amount:number|null;roles:string[];active:boolean};
export type Step = {role:string;status:string;actor?:string;at?:string;comment?:string};
export type Comment = {id:number;author:string;text:string;at:string};
export type RequestItem = {id:number;title:string;category:string;amount:number;reason:string;priority:string;status:string;owner_id:number;manager_id?:number;owner:string;department:string;created_at:string;steps:Step[];comments:Comment[];attachments:{id:number;name:string;size:number}[];version:number};
export type Audit = {id:number;actor:string;action:string;target:string;at:string};
export const categories=['Equipment','Software','Cloud resources','Access','Reimbursement','Leave','Vendor payment','Training'];
export const roles=['Employee','Manager','IT','Finance','HR','Director','Admin','Demo'];
export const people:Person[]=[{id:1,name:'Arjun Patel',email:'arjun@flowops.local',role:'Employee',department:'Engineering',manager_id:2},{id:2,name:'Md Raish',email:'raish@flowops.local',role:'Manager',department:'Engineering',manager_id:10},{id:3,name:'Neha Sharma',email:'neha@flowops.local',role:'IT',department:'IT'},{id:4,name:'Priya Singh',email:'priya@flowops.local',role:'Finance',department:'Finance'},{id:5,name:'Rohan Das',email:'rohan@flowops.local',role:'HR',department:'People'},{id:6,name:'Ananya Rao',email:'ananya@flowops.local',role:'Director',department:'Leadership'},{id:7,name:'Workspace Admin',email:'admin@flowops.local',role:'Admin',department:'Operations'},{id:8,name:'Sara Khan',email:'sara@flowops.local',role:'Employee',department:'Engineering',manager_id:2},{id:9,name:'Vikram Shah',email:'vikram@flowops.local',role:'Employee',department:'Design',manager_id:10},{id:10,name:'Meera Joshi',email:'meera@flowops.local',role:'Manager',department:'Design',manager_id:2}];
export const initialFlows:Flow[]=[{id:1,name:'Everyday equipment',category:'Equipment',min_amount:0,max_amount:19999.99,roles:['Manager'],active:true},{id:2,name:'Team equipment',category:'Equipment',min_amount:20000,max_amount:50000,roles:['Manager','IT'],active:true},{id:3,name:'High-value equipment',category:'Equipment',min_amount:50000.01,max_amount:100000,roles:['Manager','IT','Finance'],active:true},{id:4,name:'Capital purchases',category:'Equipment',min_amount:100000.01,max_amount:null,roles:['Manager','IT','Finance','Director'],active:true},...categories.slice(1).map((c,i)=>({id:i+5,name:c+' approval',category:c,min_amount:0,max_amount:null,roles:['Manager',...(c==='Leave'||c==='Training'?['HR']:c==='Access'?['IT']:c==='Reimbursement'||c==='Vendor payment'?['Finance']:['IT','Finance'])],active:true}))];
const specs:[string,string,number,number,string,string,number][]=[['MacBook Pro for development','Equipment',75000,1,'High','Pending',0],['Figma Professional · annual plan','Software',18000,8,'Normal','Pending',0],['AWS staging environment','Cloud resources',42000,1,'High','Pending',1],['Client visit · travel expenses','Reimbursement',6850,8,'Normal','Pending',0],['Production database access','Access',0,1,'Urgent','Pending',0],['Annual leave · 3 days','Leave',0,8,'Normal','Approved',2],['Dell UltraSharp 27-inch monitor','Equipment',32000,1,'Normal','Approved',2],['Notion team subscription','Software',12000,8,'Normal','Pending',2],['Q3 vendor invoice','Vendor payment',86000,1,'High','Pending',0],['React Advanced workshop','Training',4500,8,'Normal','Rejected',0],['Office accessories','Equipment',3500,1,'Normal','Approved',1],['Design workstation','Equipment',125000,9,'High','Pending',0]];
export function route(category:string,amount:number,flows:Flow[]){const f=flows.filter(x=>x.active&&x.category===category&&amount>=x.min_amount&&(x.max_amount===null||amount<=x.max_amount)).sort((a,b)=>b.min_amount-a.min_amount)[0];if(!f)throw new Error('No active workflow matches this request. Contact your administrator.');return f.roles.map((role,i)=>({role,status:i===0?'Pending':'Waiting'}));}
export const initialRequests:RequestItem[]=specs.map((s,i)=>{const [title,category,amount,owner_id,priority,status,stage]=s;const owner=people.find(p=>p.id===owner_id)!;const steps=route(category,amount,initialFlows).map((step,j)=>({...step,status:status==='Approved'?'Approved':status==='Rejected'?(j===0?'Rejected':'Waiting'):j<stage?'Approved':j===stage?'Pending':'Waiting',...(j<stage||status==='Approved'?{actor:people.find(p=>p.role===step.role)?.name,at:new Date(Date.UTC(2026,8,24-i,9)).toISOString()}: {})}));return {id:1048-i,title,category,amount,owner_id,manager_id:owner.manager_id,owner:owner.name,department:owner.department,priority,status,reason:category==='Equipment'?'Our current equipment is slowing down development and testing. This replacement will support the next product release and our daily work.':category==='Access'?'Read-only access is required to investigate a customer issue. Access is needed for seven days and can be revoked once the investigation is complete.':'Required for the team’s ongoing work. Please review the business need and the requested budget.',created_at:new Date(Date.UTC(2026,8,24-Math.floor(i/2),8+i%6,25)).toISOString(),steps,comments:[],attachments:[],version:1};});
export const initialAudit:Audit[]=[{id:1,actor:'Rohan Das',action:'Approved request',target:'REQ-1043',at:'2026-09-24T09:42:00Z'},{id:2,actor:'Arjun Patel',action:'Submitted request',target:'REQ-1048',at:'2026-09-24T08:25:00Z'},{id:3,actor:'Priya Singh',action:'Approved request',target:'REQ-1042',at:'2026-09-24T08:10:00Z'}];
export function canSee(r:RequestItem,u:Person,users:Person[]){return u.role==='Admin'||r.owner_id===u.id||u.role==='Manager'&&(r.manager_id??users.find(p=>p.id===r.owner_id)?.manager_id)===u.id||!['Employee','Manager'].includes(u.role)&&r.steps.some(s=>s.role===u.role);}
export function canApprove(r:RequestItem,u:Person,users:Person[]){return r.status==='Pending'&&r.owner_id!==u.id&&r.steps.find(s=>s.status==='Pending')?.role===u.role&&(u.role!=='Manager'||(r.manager_id??users.find(p=>p.id===r.owner_id)?.manager_id)===u.id);}
export const money=(n:number)=>n?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n):'—';
export const initials=(name:string)=>name.split(' ').map(w=>w[0]).slice(0,2).join('');
